import 'package:fit_mate_client/features/recommendation/model/recommended_product.dart';

class RecommendationRepository {
  Future<List<RecommendedProduct>> fetchByType(ClothingType type) async {
    await Future.delayed(const Duration(milliseconds: 600));
    return _mockData.where((p) => p.clothingType == type).toList();
  }
}

const List<RecommendedProduct> _mockData = [
  RecommendedProduct(
    id: 'top_1',
    name: '플로럴 미디 랩 드레스',
    brand: 'H&M',
    price: 49900,
    originalPrice: 69900,
    discountRate: 29,
    imageUrl: '',
    clothingType: ClothingType.top,
    tags: ['플로럴', '미디'],
  ),
  RecommendedProduct(
    id: 'top_2',
    name: '오버핏 리넨 블렌드 셔츠',
    brand: 'ZARA',
    price: 59900,
    imageUrl: '',
    clothingType: ClothingType.top,
    tags: ['오버핏', '리넨'],
  ),
  RecommendedProduct(
    id: 'top_3',
    name: '테일러드 크롭 재킷',
    brand: 'COS',
    price: 129000,
    imageUrl: '',
    clothingType: ClothingType.top,
    tags: ['테일러드', '크롭'],
  ),
  RecommendedProduct(
    id: 'top_4',
    name: '드라이핏 반팔 티셔츠',
    brand: 'Under Armour',
    price: 39000,
    imageUrl: '',
    clothingType: ClothingType.top,
    tags: ['운동', '기능성'],
  ),
  RecommendedProduct(
    id: 'top_5',
    name: '슬림핏 터틀넥',
    brand: 'Zara',
    price: 52000,
    originalPrice: 65000,
    discountRate: 20,
    imageUrl: '',
    clothingType: ClothingType.top,
    tags: ['겨울', '미니멀'],
  ),
  RecommendedProduct(
    id: 'top_6',
    name: '코튼 후드 집업',
    brand: 'Nike',
    price: 79000,
    imageUrl: '',
    clothingType: ClothingType.top,
    tags: ['스포티', '후드'],
  ),
  RecommendedProduct(
    id: 'btm_1',
    name: '슬림 테이퍼드 청바지',
    brand: "Levi's",
    price: 89000,
    imageUrl: '',
    clothingType: ClothingType.bottom,
    tags: ['데님', '데일리'],
  ),
  RecommendedProduct(
    id: 'btm_2',
    name: '슬림 조거 팬츠',
    brand: 'Adidas',
    price: 65000,
    originalPrice: 89000,
    discountRate: 27,
    imageUrl: '',
    clothingType: ClothingType.bottom,
    tags: ['운동', '스포티'],
  ),
  RecommendedProduct(
    id: 'btm_3',
    name: '와이드 리넨 슬랙스',
    brand: 'Zara',
    price: 69000,
    imageUrl: '',
    clothingType: ClothingType.bottom,
    tags: ['캐주얼', '여름'],
  ),
  RecommendedProduct(
    id: 'out_1',
    name: '오버핏 테크 재킷',
    brand: 'Nike',
    price: 89000,
    imageUrl: '',
    clothingType: ClothingType.outer,
    tags: ['운동', '캐주얼'],
  ),
  RecommendedProduct(
    id: 'out_2',
    name: '울 체크 코트',
    brand: 'Mango',
    price: 189000,
    originalPrice: 249000,
    discountRate: 24,
    imageUrl: '',
    clothingType: ClothingType.outer,
    tags: ['겨울', '포멀'],
  ),
  RecommendedProduct(
    id: 'shoe_1',
    name: '쿠션 러닝화',
    brand: 'New Balance',
    price: 129000,
    imageUrl: '',
    clothingType: ClothingType.shoes,
    tags: ['러닝', '기능성'],
  ),
  RecommendedProduct(
    id: 'shoe_2',
    name: '클래식 로우 스니커즈',
    brand: 'Converse',
    price: 79000,
    originalPrice: 99000,
    discountRate: 20,
    imageUrl: '',
    clothingType: ClothingType.shoes,
    tags: ['캐주얼', '데일리'],
  ),
];
